package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

type initFlags struct {
	structName string
	output     string
}

var initArgs initFlags

var initCmd = &cobra.Command{
	Use:   "init [flags] <file.go>",
	Short: "Generate a .env.example from a Go config struct",
	Long: `Parse a Go source file with env-tagged struct fields
and generate a .env.example file with keys and defaults.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		structs, err := parseGoFile(args[0])
		if err != nil {
			return fmt.Errorf("parse struct: %w", err)
		}

		s := selectStruct(structs, initArgs.structName)
		if s == nil {
			if initArgs.structName != "" {
				return fmt.Errorf("struct %q not found in %s", initArgs.structName, args[0])
			}
			return fmt.Errorf("multiple structs found; use --struct to specify which one\n\n%s", structNames(structs))
		}

		var b strings.Builder
		b.WriteString(fmt.Sprintf("# %s - Environment variables\n", s.Name))
		b.WriteString("# Auto-generated by envcontract init\n\n")

		for _, f := range s.Fields {
			comment := fmt.Sprintf("# %s (%s", f.EnvKey, f.Kind)
			if f.Required {
				comment += ", required"
			}
			comment += ")\n"

			val := ""
			if f.HasDefault {
				val = f.Default
			}

			if val == "" && f.Required {
				val = "<fill-me>"
			}

			b.WriteString(comment)
			b.WriteString(fmt.Sprintf("%s=%s\n\n", f.EnvKey, val))
		}

		output := initArgs.output
		if output == "" {
			output = ".env.example"
		}

		if err := os.WriteFile(output, []byte(b.String()), 0644); err != nil {
			return fmt.Errorf("write %s: %w", output, err)
		}

		fmt.Printf("wrote %s\n", output)
		return nil
	},
}

func init() {
	initCmd.Flags().StringVarP(&initArgs.structName, "struct", "s", "", "struct name to generate from")
	initCmd.Flags().StringVarP(&initArgs.output, "output", "o", ".env.example", "output file path")
}
